{% set name = "butane" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coreos/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1a91ea42a7d952fd91078c7492e8f813e0e69d312225ee1903c157024da7e643

build:
  script:
    - go build -v -o {{ target_gobin }}{{ name }}{{ target_goexe }} -ldflags "-w -X github.com/coreos/butane/internal/version.Raw={{ version }}" internal/main.go
    - go-licenses save ./internal --save_path=license-files
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - butane -V

about:
  home: https://coreos.github.io/butane/
  summary: Butane translates human-readable Butane Configs into machine-readable Ignition Configs.
  description: |
    Butane (formerly the Fedora CoreOS Config Transpiler, FCCT)
    translates human readable Butane Configs into machine readable
    Ignition Configs.
  license:  Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  dev_url: https://github.com/coreos/butane

extra:
  recipe-maintainers:
    - freundTech
